version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db/:/var/lib/postgresql/data/
    networks:
      - app_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app_network
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '4000:3001'
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c "sleep 10 && npm run start:prod"
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app_network

networks:
  app_network:
    name: app_network
